name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Ganti dengan nama branch kamu jika bukan 'master'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
